name: 'Monaco Deploy'
description: 'Deploy monitoring-as-code to Dynatrace'
inputs:
  url:
    description: 'Dynatrace URL'
    required: true
  token:
    description: 'Dynatrace API Token'
    required: true
  specific-environment:
    description: 'Specify environment in environments.yaml'
  project:
    description: 'Specify Monaco project'
  monaco-root:
    description: 'Specify Root for deploy'
    default: 'monitoring-as-code'
  optional-params:
    description: 'Specify Optional Parameters (ex. --dry-run, --continue-on-error, ect...)'


runs:
  using: "composite"
  steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -L https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases/download/v1.6.0/monaco-linux-amd64 -o monaco
    - name: monaco deploy
      env:
        URL: ${{ inputs.url }}
        API_TOKEN: ${{ inputs.token }}
        PROJECT: ${{ inputs.project }}
        SPECIFIC_ENVIRONMENT: ${{ inputs.specific-environment }}
        MONACO_ROOT: ${{ inputs.monaco-root }}
      run: chmod +x monaco && export NEW_CLI=1 && ./monaco deploy {{ inputs.optional-params }} --environments=$MONACO_ROOT/environments.yaml --project=$MONACO_ROOT/$PROJECT --specific-environment=$SPECIFIC_ENVIRONMENT
      shell: bash
