name: 'Monaco Deploy'
description: 'Deploy monitoring-as-code to Dynatrace'
inputs:
  url:
    description: 'Dynatrace URL'
    required: true
  token:
    description: 'Dynatrace API Token'
    required: true
  specific-environment:
    description: 'Specify environment in environments.yaml'
  project:
    description: 'Specify Monaco project'
  

runs:
  using: "composite"
  steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -L https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases/download/v1.6.0/monaco-linux-amd64 -o monaco
    - name: monaco deploy
      env:
        URL: ${{ inputs.url }}
        API_TOKEN: ${{ inputs.token }}
        PROJECT: ${{ inputs.project }}
        SPECIFIC_ENVIRONMENT: ${{ inputs.specific-environment }}
      run: chmod +x monaco && export NEW_CLI=1 && ./monaco deploy --environments=monitoring-as-code/environments.yaml --project=monitoring-as-code/$PROJECT --specific-environment=$SPECIFIC_ENVIRONMENT
      shell: bash
